version: '3.8'

services:
  app:
    image: ${DOCKER_HUB_USERNAME}/ngkbot:latest
    container_name: ngk_bot
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - BOT_API=${BOT_API}
      - JWT_SECRET=${JWT_SECRET}
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_GROUP_ID=${ADMIN_GROUP_ID}
    command: npm start
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: ngk_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: